### PR TITLE
AutoIndy Page Addition Adjustments

### PR DESCRIPTION
**Pull request by xinkecf35**
This PR largely takes the base work from [PR 17](https://github.com/Pitt-RAS/Pitt-RAS.github.io/pull/17) and adds the changes as noted. Most major and notable change is that the copy/content of the page has been redone as much as possible using Markdown. This PR primary purpose is to move content out of the templates into an appropriate Markdown file as the purpose of Jekyll is the ability to use Markdown as a means of managing content. A summary of changes is as follows:

- Modified images assets as they existed in the IGVC_edits branch to be consistent
- Brought copy in from original work into Markdown
- Edited text for tone/proofreading
- Adjusted formatting to maintain consistency with current website content

With the changes above, an indirect goal/consequence of the work here is effectively a demonstration of what Markdown can do when combined with Jekyll and the ease of doing so. Wherever possible, content was brought in using purely Markdown formatting, reverting to HTML when necessary. These largely included cases where content needed CSS styles to applied in order to achieve aspecific aesthetic as guided by the original work from the IGVC_edits branch.

Below are PDFs of generated static site with these changes. Please note the web preview from Dropbox is of lower resolution than the actual site.

https://www.dropbox.com/s/ro1pn8m2w7l3kh5/home_render.pdf?dl=0
https://www.dropbox.com/s/dc5qtmls4eog6pg/indy_render.pdf?dl=0
https://www.dropbox.com/s/evrcv9pjz0sykfb/projects_render.pdf?dl=0

### CODE REVIEW

**Comment by nls5260** [comment]
I like the layout of our previous Indy page better. But, I like the addition of the current projects part in the projects list. Could we use the old page but just tidy it up a bit.

**Comment by nls5260** [comment]
I agree with you that the current layout would help, but due to the scale of the project, I wanted to polish it up a bit. The old page I feel reflects that sentiment. We could create a new template for the Indy page (or similar large projects) but for now, I'd like to keep the previous Indy page as the project page.

**Comment by xinkecf35** [comment]
My primary objection and concern is that the manner in the way that page was already added completely subverts the purpose of using Jekyll, hence the content of this PR. The use of markdown is meant to simplify the process of making content.

Now, I don't really find HTML hard to write but for the uninitiated, the ability to use Markdown is extremely useful and convenient. Not to mention not needing to worry about how on earth CSS/Bootstrap works is a big plus in my book.

**Comment by xinkecf35** [comment]
Seeing work in PR 17, closing

**Pull request closed without merging**
